pipeline {
    agent {
        label 'sdk-ecube-1.1.0'
    }
    environment {
        SYSROOTS = "${env.SYSROOTS_1_1_0}"
    }
    triggers {
        bitbucketPush()
    }
    stages {
        stage('Build (Release)') {
            steps {
                sh '''
                    LD_LIBRARY_PATH= . ${SYSROOTS}/../environment-setup-aarch64-poky-linux
                    make
                '''
            }
        }
        stage('Coding style') {
            steps {
                sh 'make clangcheck'
            }
        }
        stage('Documentation') {
            steps {
                sh 'make doc'
            }
        }
        stage('Package Delivery') {
            steps {
                sh '''
                LD_LIBRARY_PATH= . ${SYSROOTS}/../environment-setup-aarch64-poky-linux
                make package
                '''
            }
        }
        stage('Publish') {
            when {
                anyOf {
                    branch "master"
                    branch "release/*"
                }
            }
            environment {
               VERSION = sh(script: './test/version.sh', , returnStdout: true).trim()
            }
            steps {
                nexusPublisher nexusInstanceId: 'Nexus3', nexusRepositoryId: 'eCube-releases', packages:
                    [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: 'tar', filePath: "build/eviewitf-${env.VERSION}.tar"]],
                        mavenCoordinate: [artifactId: 'eviewitf', groupId: 'group.lacroix.ecube', packaging: 'tar', version: "${env.VERSION}"]]]
            }
        }
        stage('Publish feature branch') {
            when {
                anyOf {
                    branch "release-test/*"
                }
            }
            environment {
                VERSION = sh(script: './test/version.sh', , returnStdout: true).trim()
                NEXUS_ARTIFACT_NAME = sh(script: './test/version.sh --nexus', , returnStdout: true).trim()
            }
            steps {
                nexusPublisher nexusInstanceId: 'Nexus3', nexusRepositoryId: 'eCube-releases', packages:
                    [[$class: 'MavenPackage', mavenAssetList: [[classifier: '', extension: 'tar', filePath: "build/eviewitf-${env.VERSION}.tar"]],
                        mavenCoordinate: [artifactId: 'eviewitf', groupId: 'group.lacroix-test.ecube', packaging: 'tar', version: "${env.NEXUS_ARTIFACT_NAME}"]]]
            }
        }

    }
    post {
        always {
            script {
                currentBuild.result = currentBuild.result ?: 'SUCCESS'
                deleteDir();
            }
        }
    }
}
